services:
  sender:
    build:
      context: ./scripts
    volumes:
      - ./data:/data
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend